name: example
description: A sample command-line application.
version: 1.0.0
publish_to: none
# homepage: https://www.example.com

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  path: ^1.8.0
  http: ^0.13.4
  dartz: ^0.10.1
  http_service1:
    path: ../

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
